rules:
  - path: /view/indicators
    methods: ["GET"]
    request_headers:
      x-auth: asdf
      x-auth-hash: "{x-auth-hash:.*}"
      accept: "application/json"
      accept-version: "2.6"
    query_params:
      startDate: "{startDate:.*}"
      endDate: "{endDate:.*}"
    responses:
      - status_code: 200
        body: |-
          {
            "success": true,
            "message": [{
              "reportId": "17-00006345",
              "title": "CMS-API-Microsoft-Malware-One-Indicator-Executive",
              "ThreatScape": "Cyber Physical",
              "audience": "Executive",
              "intelligenceType": "malware",
              "publishDate": 1493196720,
              "reportLink": "https://api.isightpartners.com/report/17-00006345",
              "webLink": "https://mysight.isightpartners.com/report/full/17-00006345",
              "emailIdentifier": null,
              "senderAddress": null,
              "senderName": null,
              "sourceDomain": null,
              "sourceIp": null,
              "subject": null,
              "recipient": null,
              "emailLanguage": null,
              "fileName": null,
              "fileSize": null,
              "fuzzyHash": null,
              "fileIdentifier": null,
              "md5": null,
              "sha1": null,
              "sha256": null,
              "description": null,
              "fileType": null,
              "packer": null,
              "userAgent": null,
              "registry": null,
              "fileCompilationDateTime": null,
              "filePath": null,
              "asn": null,
              "cidr": null,
              "domain": "domain4.com",
              "domainTimeOfLookup": null,
              "networkIdentifier": "Victim",
              "ip": "10.10.10.10",
              "port": null,
              "protocol": null,
              "registrantEmail": null,
              "registrantName": null,
              "networkType": "network",
              "url": null,
              "malwareFamily": null,
              "malwareFamilyId": null,
              "actor": null,
              "actorId": null,
              "observationTime": 1493196720,
              "version": "1"
            },
            {
              "reportId" : "16-00011458",
              "title" : "Elirks Campaign Likely Associated with Japan Tourist Bureau Breach",
              "ThreatScape" : "Cyber Espionage",
              "audience" : "Operational",
              "intelligenceType" : "threat",
              "publishDate" : 1469544180,
              "reportLink" : "https://api.isightpartners.com/report/16-00011458",
              "webLink" : "https://mysight.isightpartners.com/report/full/16-00011458",
              "emailIdentifier" : null,
              "senderAddress" : null,
              "senderName" : null,
              "sourceDomain" : null,
              "sourceIp" : null,
              "subject" : null,
              "recipient" : null,
              "emailLanguage" : null,
              "fileName" : "TW2BBFF500.doc",
              "fileSize" : 14860,
              "fuzzyHash" : "384:AmHWrWG6qqrx7F7ByIvjgS+S0SBS1n9dwnHJWNy/4yAOksmSfsF17BtX7K4:qrWG6qqV7F7ByIvjgS+S0SBSd9dwnHJw",
              "fileIdentifier" : "Related",
              "md5" : "d27eb3f18ba7f3ae6fa793630882652f",
              "sha1" : "4559ba637772b681dee07127c7c17c776455138e",
              "sha256" : "e9c60a120db8a4366734dcecbc15ddd4510ef7929cc7a5d21529180494a35cdc",
              "description" : null,
              "fileType" : "Rich Text Format data, version 1, ANSI",
              "packer" : null,
              "userAgent" : null,
              "registry" : null,
              "fileCompilationDateTime" : null,
              "filePath" : null,
              "asn" : null,
              "cidr" : null,
              "domain" : null,
              "domainTimeOfLookup" : null,
              "networkIdentifier" : null,
              "ip" : null,
              "port" : null,
              "protocol" : null,
              "registrantEmail" : null,
              "registrantName" : null,
              "networkType" : null,
              "url" : null,
              "malwareFamily" : null,
              "malwareFamilyId" : null,
              "actor" : null,
              "actorId" : null,
              "observationTime" : 1469544180
            }]
          }
