version: '2.3'
services:
  aws-emulator:
    image: localstack/localstack
    ports:
      - "443:443"
    environment:
      - SERVICES=s3,sqs
      - EDGE_PORT=443
      - SQS_PROVIDER=elasticmq
    networks:
      elastic-package-stack_default:
        aliases:
          - sqs.ab-test-0.amazonaws.com
          - s3.ab-test-0.amazonaws.com
          - cloudtrail.s3.ab-test-0.amazonaws.com
          - firewall.s3.ab-test-0.amazonaws.com
  aws-firewall-logs:
    image: amazon/aws-cli
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ./configs:/aws/configs:ro
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: ab-test-0
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10h
        aws --no-verify-ssl --endpoint-url https://aws-emulator s3api create-bucket --bucket firewall --create-bucket-configuration LocationConstraint=ab-test-0
        aws --no-verify-ssl --endpoint-url https://aws-emulator sqs create-queue --queue-name firewall --region ab-test-0
        sed 's/##REGION##/ab-test-0/g; s/##QUEUE##/firewall/g' configs/sqs-notification.json > sqs-notification.json
        aws --no-verify-ssl --endpoint-url https://aws-emulator s3api put-bucket-notification-configuration --bucket firewall --notification-configuration file://sqs-notification.json
        aws --no-verify-ssl --endpoint-url https://aws-emulator s3 cp /sample_logs/firewall.log s3://firewall
    depends_on:
      - aws-emulator
    networks:
      - elastic-package-stack_default
networks:
  elastic-package-stack_default:
    external: true